
apiVersion: v1
kind: Namespace
metadata:
  name: databases
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: databases
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: db
          image: mongo:3.6
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: databases
spec:
  type: ClusterIP # Default Type
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
